# PG Selector
apiVersion: v2
name: hitman
type: application
description: >-
  A Helm chart for Hitman, a daemon for Kubernetes to kill 
  target resources under user-defined templated conditions
version: 0.1.0 # chart version
appVersion: "0.1.0" # pg-selector version
kubeVersion: ">=1.22.0-0" # kubernetes version
home: https://github.com/achetronic/hitman
sources:
  - https://github.com/achetronic/hitman
keywords:
  - hitman
  - kubernetes
maintainers:
  - name: Alby Hernández
    email: donfumero@gmail.com.com
    url: https://github.com/achetronic/hitman

