version: v1alpha1
kind: Hitman
metadata:
  name: notification-sample-simple
spec:
  synchronization:
    time: 1m

  resources:

    - target:
        group: ""
        version: v1
        kind: Pod
        name: pepito
        namespace: juanito
        
      conditions:
      - key: |
          {{ .status.startTime  > 1h }}
        value: true
