version: v1alpha1
kind: Config
metadata:
  name: access-to-reports
spec:
  # Source of data to be served. 
  # This section can be extended to support other sources like S3, Azure Blob Storage, etc.
  source:
    gcs:
      bucket: general-purposes-bucket
      credentials:
        path: /tmp/credentials.json

  # Web server configuration
  # Here it's the place to define the server configuration like port, host, credentials, etc.
  webServer:
    listener:
      port: 9090
      host: localhost

    # Several credentials can be defined
    credentials:
      - type: "bearer"
        token: "12345xxxx12345"

      - type: "bearer"
        token: "6789yyyy6789"
      
      - type: "bearer"
        token: "${TOKEN_FROM_ENV}"

    # Routes must be defined to allow access to the data
    # They are defined as golang regular expressions
    # Remember: negative lookbehind is not supported
    allowedTargets:
      - route: "^/qa-reports/(.*).json$"
      - route: "^/pipelines-results/(.*).json$"
