{{ if .Values.agent.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bucketSimpleServer.fullname" . }}-agent-config
  labels:
    {{- include "bucketSimpleServer.labels" . | nindent 4 }}
data:
  bucketSimpleServer.yaml: |-
    {{- .Values.agent.config | nindent 4 }}
{{- end }}